apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: o9yx6opf6-nodejs 
  janus-idp.io/tekton: o9yx6opf6-nodejs
  backstage.io/kubernetes-id: o9yx6opf6-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o9yx6opf6-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml